version: '3.1'

networks:
  monitoring:

services:
  icinga.zylk.net:
    build: .
    networks:
      monitoring:
    ports:
      - 8888:80
    environment:
      - MODE=CE
      - ALF_HOST=alfresco5ce.zylk.net
      - ALF_PORT=8080 
      - ALF_USER=${ALF_USER} 
      - ALF_PASS=${ALF_PASSWORD}
      - JMXPROXY_USER=${JMXPROXY_USER}
      - JMXPROXY_PASS=${JMXPROXY_PASS}    
      - JMX_USER=${JMX_USER}
      - JMX_PASS=${JMX_PASS} 
      - ASS_HOST=solr6ce.zylk.net
      - ASS_PORT=8983 

      #- MODE=EE
      #- ALF_HOST=alfresco5ee.zylk.net
      #- ALF_PORT=8080 
      #- ALF_USER=${ALF_USER} 
      #- ALF_PASS=${ALF_PASSWORD}
      #- JMXPROXY_USER=${JMXPROXY_USER}
      #- JMXPROXY_PASS=${JMXPROXY_PASS}    
      #- JMX_USER=${JMX_USER}
      #- JMX_PASS=${JMX_PASS} 
      #- ASS_HOST=solr6ee.zylk.net
      #- ASS_PORT=8983 

    extra_hosts:
      - "alfresco5ce.zylk.net:192.168.1.100"
      - "solr6ce.zylk.net:192.168.1.101"
      #- "alfresco5ee.zylk.net:192.168.1.200"
      #- "solr6ee.zylk.net:192.168.1.201"